from django.urls import path
from project import views

urlpatterns = [
    path(r'project/', views.project_obj, name='project'),
    path(r'project/index', views.project_index, name='project_index'),
    path(r'project/<int:id>', views.project_show, name='project_show'),
    path(r'project/add/<type>', views.project_add, name='project_add'),
    path(r'project/<int:id>/change/', views.project_edit, name='project_change'),
    path(r'project/api/', views.project_api),
    path(r'task/', views.task_obj, name='task'),
    path(r'task/index/', views.task_index, name='task_index'),
    path(r'task/<int:id>/', views.task_show, name='task_show'),
    path(r'task/add/', views.task_add, name='task_add'),
    path(r'task/<int:id>/change/', views.task_edit, name='task_edit'),
    path(r'projectflow/add/', views.flow_add, name='flow_add'),
    path(r'projectflow/<id>/change/', views.flow_edit, name='flow_change'),
    path(r'projectflow/', views.flow_index, name='flow'),
    path(r'examine/', views.examine_obj, name='examine'),
    path(r'examine/<int:id>/change/', views.examine_edit, name='examine_change'),
    path(r'delay/', views.delay_obj, name='delay'),
    path(r'delay/<int:id>/change/', views.delay_edit, name='delay_change'),
    # path(r'delete/api/',views.delete_api),
    path(r'upload/api/', views.upload),
    path(r'task_status/api/', views.task_status),
    path(r'contribution/', views.contribution_obj, name='contribution'),
    path(r'contribution/add/', views.contribution_add, name='contribution_add'),
    path(r'contribution/<int:id>/', views.contribution_show, name='contribution_show'),
    path(r'contribution/<int:id>/change/', views.contribution_edit, name='contribution_edit'),
    path(r'notice/', views.notice, name='notice'),
    path(r'notice/new/', views.new_notice),
    path(r'file/project/', views.file_project, name='file_project'),
    path(r'file/', views.file_obj, name='file'),
    path(r'delay/api/', views.delay_add),
    path(r'node/api/', views.project_node_file, name='node_file'),
    path(r'image/api/', views.image, name='node_file'),
]
